-- NeuroSense Database Schema
-- Optimized for PostgreSQL and Supabase Realtime Clinical Sync

-- Enable UUID extension if needed (Standard in Supabase)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (CASCADE removes dependent objects)
DROP TABLE IF EXISTS connections CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table (Core Registry)
-- Stores basic credentials and common identity data.
-- Plain text password storage is maintained as per user request.
CREATE TABLE users (
    id TEXT PRIMARY KEY, -- Compatible with application UUID/String format
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    password TEXT NOT NULL, -- Plain text storage
    role TEXT NOT NULL CHECK (role IN ('PATIENT', 'DOCTOR')),
    start_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Profiles Table (Role-Specific Metadata)
-- Stores data unique to patients (diagnosis) or doctors (license)
CREATE TABLE profiles (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    diagnosis TEXT, -- For Patients
    case_id TEXT, -- For Patients
    license_id TEXT, -- For Doctors
    is_verified BOOLEAN DEFAULT FALSE -- For Doctors
);

-- 3. Sessions Table (Bio-Telemetry History)
-- Uses identity for efficient indexing and TIMESTAMPTZ for global accuracy
CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('BODY', 'BRAIN', 'SPEECH', 'MENTAL')),
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 100),
    feedback TEXT
);

-- 4. Connections Table (Clinical Handshake)
CREATE TABLE connections (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doctor_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('IDLE', 'PENDING', 'CONNECTED')),
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(patient_id, doctor_id) -- Prevents duplicate links
);

-- Performance Indexes
CREATE INDEX idx_sessions_patient ON sessions(patient_id);
CREATE INDEX idx_connections_doctor ON connections(doctor_id);
CREATE INDEX idx_sessions_timestamp ON sessions(timestamp);

-- Row-Level Security (RLS) Policies
-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE connections ENABLE ROW LEVEL SECURITY;

-- Users Table Policies
-- Allow anyone to register (INSERT) - Critical for signup
CREATE POLICY "Allow public user registration" ON users
    FOR INSERT
    WITH CHECK (true);

-- Allow users to read their own data
CREATE POLICY "Users can read own data" ON users
    FOR SELECT
    USING (true); -- Allow all reads for simplicity in this app

-- Allow users to update their own data
CREATE POLICY "Users can update own data" ON users
    FOR UPDATE
    USING (true);

-- Profiles Table Policies
CREATE POLICY "Allow profile creation" ON profiles
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Users can read profiles" ON profiles
    FOR SELECT
    USING (true);

CREATE POLICY "Users can update profiles" ON profiles
    FOR UPDATE
    USING (true);

-- Sessions Table Policies
CREATE POLICY "Allow session creation" ON sessions
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Users can read sessions" ON sessions
    FOR SELECT
    USING (true);

-- Connections Table Policies
CREATE POLICY "Allow connection creation" ON connections
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Users can read connections" ON connections
    FOR SELECT
    USING (true);

CREATE POLICY "Users can update connections" ON connections
    FOR UPDATE
    USING (true);

-- Supabase Realtime Setup
-- To enable real-time updates for these tables, run:
-- alter publication supabase_realtime add table sessions;
-- alter publication supabase_realtime add table users;
-- alter publication supabase_realtime add table connections;
